spring:
  data:
    mongodb:
      username: customer
      password: customer
      host: localhost
      port: 27018
      database: customer
      authentication-database: admin


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:4050/eureka/